name: Angular CI

on:
  push:
    branches: [dev] # Déclenchement sur les pushs vers la branche dev
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    name: Build and Test Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build app
        run: npm run build -- --configuration production
